CREATE TABLE IF NOT EXISTS EMPLOYEES(
ROLL_NO TEXT PRIMARY KEY,
NAME TEXT NOT NULL,
ADDRESS TEXT,
PHONE TEXT,
AGE INTEGER
);

INSERT INTO EMPLOYEES (ROLL_NO , NAME , ADDRESS , PHONE , AGE) VALUES
('1', 'JAY', 'DELHI', '*****', 18),
('2', 'HARSH', 'JAIPUR', '*****', 18),
('3', 'SUJIT', 'MUMBAI', '*****', 20),
('4', 'SURESH', 'DELHI', '*****', 18),
('5', 'AMAN', 'MUMBAI', '*****', 20),
('6', 'HARSH', 'JAIPUR', '*****', 18);

SELECT * FROM EMPLOYEES;

SELECT * FROM EMPLOYEES WHERE AGE = 18 AND NAME = "HARSH";

SELECT * FROM EMPLOYEES WHERE NAME= "JAY" OR NAME = "SUJIT";

SELECT * FROM EMPLOYEES WHERE AGE = 18 AND (NAME = "JAY" OR NAME="HARSH");